### Add Sensor Data
POST http://localhost:8080/end-device/sensor-data/add-sensor-data
Content-Type: application/json

{
  "endDeviceMac": "AA:BB:CC:DD:EE:FF",
  "sensors": [
    {
      "sensorNumber": 1,
      "sensorValues": [
        {
          "timestamp": "2024-11-11T11:10:00",
          "value": "23.5"
        },
        {
          "timestamp": "2024-11-11T11:11:00",
          "value": "24.0"
        }
      ]
    },
    {
      "sensorNumber": 2,
      "sensorValues": [
        {
          "timestamp": "2024-11-11T11:10:00",
          "value": "18.7"
        },
        {
          "timestamp": "2024-11-11T11:11:00",
          "value": "19.1"}
      ]
    }
  ]
}

### Get Sensor Data by Sensor Number
GET http://localhost:8080/end-device/sensor-data/AA:BB:CC:DD:EE:FF/sensor/1?start=2024-11-11T00:00:00&stop=2024-11-11T11:10:00

### Get All Sensor Data
GET http://localhost:8080/end-device/sensor-data/AA:BB:CC:DD:EE:FF

### Create Sensor Value
POST http://localhost:8080/end-device/sensor-data/add-sensor-value
Content-Type: application/json

{
  "endDeviceMac": "00:1A:22:33:44:55",
  "sensorNumber": 1,
  "timestamp": "2023-10-10T12:34:56.789",
  "value": "25.7"
}

### Create Sensor Values
POST http://localhost:8080/end-device/sensor-data/add-sensor-values
Content-Type: application/json

[
  {
    "metaField": {
      "endDeviceMac": "AA:BB:CC:DD:EE:FF",
      "sensorNumber": 3
    },
    "timestamp": "2024-11-13T16:30:00",
    "value": "43"
  },
  {
    "metaField": {
      "endDeviceMac": "BB:BB:CC:DD:EE:FF",
      "sensorNumber": 4
    },
    "timestamp": "2024-11-13T16:30:00",
    "value": "24"
  }
]